- name: multilib-Repo aktivieren
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist'
    replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"

- name: Parallele Downloads in pacman aktivieren
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads'
    line: "ParallelDownloads = {{ sarch_parallel_downloads }}"

- name: Mirrorlist mit reflector erzeugen
  when: sarch_reflector.enabled | bool
  become: true
  block:
    - name: reflector installieren
      community.general.pacman:
        name: reflector
        state: present
    - name: Mirrorlist schreiben
      ansible.builtin.command: >
        reflector --sort rate --latest 20 --protocol https
        --country {{ sarch_reflector.country }}
        --save /etc/pacman.d/mirrorlist
      changed_when: true

- name: Paketdatenbank aktualisieren
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Systemupdate (offizielle Pakete)
  when: sarch_upgrade | bool
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
