windowrule = fullscreen 1, match:workspace 4
windowrule = workspace 1, match:class steam_app_default, match:title Hearthstone
#windowrule = workspace 1, fullscreen 1, class:hearthstone.exe
#windowrule = workspace 1, fullscreen 1, class:steam_app_2767030
# Windows durchsichtig ausser Maximiert.
windowrule = opacity 0.8 0.8, match:class ^(.*)$
# Würde auch mit Silent gehen
# windowrulev2 = workspace 1 silent, fullscreen, class:hearthstone.exe

windowrule = float 1, match:class ^org.pulseaudio.pavucontrol$
windowrule = center 1, match:class ^org.pulseaudio.pavucontrol$

layerrule = blur 1, match:class ^(rofi)$
#layerrule = ignorezero 1, match:class = ^(rofi)$